### ISSUE TITLE
Malware report on windows

### ISSUE THREAD

**Issue by FranciscoAmestoy** [Loukious/StreamLabsTikTokStreamKeyGenerator#12]
Latest .exe version is blocked in Chrome also flagged in defender as malware?

**Comment by Loukious** [comment]
It's normal because it's of "unknown" source.

**Comment by SicariusK9** [comment]
Just a heads up it's not just the typical unknown source error/flag. It's an actual malware flag for the Wacatac.B!Ml trojan in the 0.0.7 release .exe that defender is throwing and likely also why chrome blocked it.

0.0.6 release is tested clear and chrome had no issues with.

**Comment by Loukious** [comment]
> Just a heads up it's not just the typical unknown source error/flag. It's an actual malware flag for the Wacatac.B!Ml trojan in the 0.0.7 release .exe that defender is throwing and likely also why chrome blocked it.
> 
> 0.0.6 release is tested clear and chrome had no issues with.

It's called a false flag for a reason. Because, you know, it's a false flag. It won't always be the same. The difference between the version 0.0.6 and 0.0.7 is very minor. Only two commits:
https://github.com/Loukious/StreamLabsTikTokStreamKeyGenerator/commit/4b1dadde84f049070a45d4e0045e18e503937fd1
https://github.com/Loukious/StreamLabsTikTokStreamKeyGenerator/commit/14993944e32e12f4e1df28af0ed08035a89732ab
And all builds are generated and uploaded by github actions directly from source https://github.com/Loukious/StreamLabsTikTokStreamKeyGenerator/actions/runs/10356237364

Also it's open source, feel free to download it and build it yourself.
